#conditional statements
#example 1

# age=int(input("age:"))
# if(age>=18):
#   print("eligible to vote")
# else:
#    print("not eligible to vote")



#example 2
# light=input("light:")
# if(light=="red"):
#   print("stop")
# elif(light=="yellow"):
#   print("look")
# elif(light=="green"):
#   print("go")
# else:
#      print("light is broken") 
    

#   #example 3
#   #nested if

age=int(input("age:"))  
if(age>=18):
       if(age>=80):
          print("can drive")
       else:
          print("cannot drive")  

else:
     print("cannot vote")        












